name: Node.js CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ${{ matrix.os }}
    name: Buid and Test

    strategy:
      matrix:
        node-version: [14.x, 16.x, 18.x]
        os: ubuntu-latest
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/checkout@v3

      - name: Install pnpm
        uses: pnpm/action-setup@v2
        with:
          version: 8

      - name: Install dependencies
        run: pnpm install

      - name: Build
        run: pnpm run build --if-present

      - name: Test
        run: pnpm test
